name: Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: ⚙ Install stable toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: 🔬 Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.18.0'

      - name: 🆙 Upload to codecov.io
        uses: codecov/codecov-action@v2

      - name: 💾 Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
